### PR TITLE
Russian translation of README.md

### PR DESCRIPTION
**Pull request by mistbow-git**
Hi! I think it will be very helpful for the popularization OZZO in Russia.

### CODE REVIEW

**Comment by qiangxue** [comment]
Could you please put the translation in a subdirectory "translations" and then add a link to the translated version in the main README.md? This will make the project folder more organized and allow readers to more easily find your translation. Thanks!

**Comment by mistbow-git** [comment]
Thanks! May be docs/ru-RU?

**Comment by qiangxue** [comment]
Let's use `docs/README-ru.md`, at least for now. If in future we want to add other doc formats, we can reorganize it, although I think this is not likely to happen. In general, I want every ozzo repo to be simple enough to be documented in a single README.

**Comment by mistbow-git** [comment]
Hi, Qiang! I make the necessary changes. Please check whether all right?
https://github.com/mistbow-git/ozzo-routing

**Comment by qiangxue** [comment]
Could you resolve the conflict? Thanks.

**Comment by mistbow-git** [comment]
Yes! Now it's ok!

**Comment by qiangxue** [comment]
:+1:

**Pull request merged**
